name: GitHub-Profile-Summary-Cards

on:
  create:
  push:
  schedule: # execute every 24 hours
    - cron: "* */24 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v2
      - uses: ervitis/github-profile-summary-cards-v2@release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          --theme: solarized_dark
      - run: find ./profile-summary-card-output -mindepth 1 -name ${CARD_FOLDER} -prune -o -exec rm -rf {} \;
        env:
          CARD_FOLDER: solarized_dark
        continue-on-error: true
